### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by dev4dev** [ololabs/olo-pay-ios-sdk-releases#5]
Hi,

We had a crash that was produced by this line of code 

https://github.com/ololabs/olo-pay-ios-sdk-releases/blob/8502c489f6a5ce40d83425beefaec9b148c06b69/src/OloPaySDK/OloPaySDK/API/OloPayAPI.swift#L195

I don't think it is acceptable to use `try!` in production, it should be handled in a proper way.

Thank you

**Comment by magouyaware** [comment]
Sorry we didn't see this sooner. We have created a ticket and it will be addressed in the next release.

**Comment by magouyaware** [comment]
@dev4dev This has been fixed in [v4.0.2](https://github.com/ololabs/olo-pay-ios-sdk-releases/releases/tag/4.0.2). Please see the [changelog](https://github.com/ololabs/olo-pay-ios-sdk-releases/blob/main/Changelog.md#v402-jun-20-2024) for details. Feel free to reopen if you still encounter issues.

**Comment by dev4dev** [comment]
Thanks for the update, but I don't work there anymore 😄

**Comment by nbeadman** [comment]
@magouyaware Thanks for the fix, I do work for the same organization as @dev4dev when he created this issue. It can be closed based on the changes implemented in 4.0.2
